### ISSUE TITLE
Unable to get the instantiated db reference.

### ISSUE THREAD

**Issue by mehtamohit987** [jedireza/hapi-mongo-models#72]
Refer the log

Uncaught error: Cannot read property 'collection' of undefined, stack: TypeError: Uncaught error: Cannot read property 'collection' of undefined.

TypeError: Uncaught error: Cannot read property 'collection' of undefined
<     at Function.insertOne (/Users/mohitmehta/Documents/repository/server/src/albums/node_modules/mongo-models/index.js:449:42)
<     at Function.create (/Users/mohitmehta/Documents/repository/server/src/albums/models.js:15:12)

The complete log is:
< 170811/052500.156, [error] message: Uncaught error: Cannot read property 'collection' of undefined, stack: TypeError: Uncaught error: Cannot read property 'collection' of undefined
<     at Function.insertOne (/Users/mohitmehta/Documents/repository/server/src/albums/node_modules/mongo-models/index.js:449:42)
<     at Function.create (/Users/mohitmehta/Documents/repository/server/src/albums/models.js:15:12)
<     at Controller.albums (/Users/mohitmehta/Documents/repository/node_modules/hapi-albums-api/controllers.js:22:15)
<     at Object.internals.handler (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/handler.js:101:51)
<     at request._protect.run (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/handler.js:32:23)
<     at internals.Protect.run (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/protect.js:60:12)
<     at exports.execute (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/handler.js:26:22)
<     at each (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/request.js:416:16)
<     at iterate (/Users/mohitmehta/Documents/repository/node_modules/items/lib/index.js:36:13)
<     at done (/Users/mohitmehta/Documents/repository/node_modules/items/lib/index.js:28:25)
< Debug: internal, implementation, error
<     TypeError: Uncaught error: Cannot read property 'collection' of undefined
<     at Function.insertOne (/Users/mohitmehta/Documents/repository/server/src/albums/node_modules/mongo-models/index.js:449:42)
<     at Function.create (/Users/mohitmehta/Documents/repository/server/src/albums/models.js:15:12)
<     at Controller.albums (/Users/mohitmehta/Documents/repository/node_modules/hapi-albums-api/controllers.js:22:15)
<     at Object.internals.handler (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/handler.js:101:51)
<     at request._protect.run (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/handler.js:32:23)
<     at internals.Protect.run (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/protect.js:60:12)
<     at exports.execute (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/handler.js:26:22)
<     at each (/Users/mohitmehta/Documents/repository/node_modules/hapi/lib/request.js:416:16)
<     at iterate (/Users/mohitmehta/Documents/repository/node_modules/items/lib/index.js:36:13)
<     at done (/Users/mohitmehta/Documents/repository/node_modules/items/lib/index.js:28:25)
< 170811/052500.156, [response] http://127.0.0.1:3000: get /api/v1/albums {} 500 (9573ms)

**Comment by mehtamohit987** [comment]
Sorry. I had to include dynamic addition of the models depending on the usage in a plugin.
